name: samm-pdf-builder
on: push
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir $HOME/datafiles
            mv ${{ github.workspace }}/* $HOME/datafiles/
            mkdir $HOME/output

        - name: "exploration"
          run: |
            echo "github.workspace is ${{ github.workspace }}"
            ls -al ${{ github.workspace }}
            echo "github.home is $HOME"
            ls -al $HOME
         
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: "process datafiles"
              uses: docker://nessimk/samm2cloudpdf:0.9
              with:
                options: "-v ${{ github.home }}:/mine"
                args: "/static.default /mine/datafiles /mine/output"
    upload:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: ${{ github.home }}/output/pdf/
