name: samm-pdf-builder
on: push
jobs:
    generate-pdf:
        # runs
        runs-on: ubuntu-latest
        steps:
        - name: checkout datafiles
          uses: actions/checkout@v2

        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: $GITHUB_WORKSPACE/output/pdf/

        services:
            yaml2pdf:
                image: nessimk/samm2cloudpdf:0.9
                volumes:
                    - /github/workspace/output:/output
                    - /github/workspace/static:/static.user
                    - /github/workspace/samm-datafiles:/app/Datafiles
