name: samm-pdf-builder
on: push
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.home }}/datafiles
            mv ${{ github.workspace }}/* ${{ github.home }}/datafiles
            mkdir ${{ github.home }}/output

        - name: "exploration"
          run: |
            echo "github.workspace is ${{ github.workspace }}"
            echo "github.home is ${{ github.home }}"
            ls -al ${{ github.home }}
            ls -al ${{ github.workspace }}
         
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: "process datafiles"
              uses: docker://nessimk/samm2cloudpdf:0.9
              with:
                args: "/static.default /github/home/datafiles /github/home/output"
    upload:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: ${{ github.home }}/output/pdf/
