name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output

        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.10
          with:
            args: "/github/workspace/static /github/workspace/datafiles /github/workspace/output"

        - name: "export pdf name"
          run: |
            short_hash=$(git rev-parse --short "$GITHUB_SHA")
            filename="samm2-${short_hash}.pdf"

          env:
            pdf_filename={{ samm2-$(git rev-parse --short "$GITHUB_SHA").pdf }}

        - name: "upload pdf"
          uses: actions/upload-artifact@v2
          with:
            name: *
            path: ${{ github.workspace }}/output/pdf/
