name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output
            #mkdir ${{ github.workspace }}/datafiles
            #mv ${{ github.workspace }}/*.yml ${{ github.workspace }}/datafiles/

        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.10
          with:
            args: "/github/workspace/static /github/workspace/datafiles /github/workspace/output"

        - name: "rename the pdf"
          run: |
            mv ${{ github.workspace }}/output/pdf/samm2.pdf ${{ github.workspace }}/output/pdf/samm2-${GITHUB_SHA}.pdf
         
        - name: "upload pdf"
          uses: actions/upload-artifact@v2
          with:
            name: samm2-${GITHUB_SHA}.pdf
            path: ${{ github.workspace }}/output/pdf/
