name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/datafiles
            mv ${{ github.workspace }}/*.yml ${{ github.workspace }}/datafiles/
            mkdir ${{ github.workspace }}/output

        - name: "exploring"
          run: |
            echo "github.workspace is ${{ github.workspace }}"
            ls -al ${{ github.workspace }}
         
        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.9
          with:
            args: "/static.default /github/workspace/datafiles /github/workspace/output"

        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: /github/workspace/output/pdf/
