name: samm-pdf-builder
on: push
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: "process datafiles"
              uses: docker://nessimk/samm2cloudpdf:0.9
              with:
                args: "-v ${{ github.workspace }}/samm-datafiles:/app/Datafiles -v ${{ github.workspace }}/output:/output"
    upload:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: ${{ github.workspace }}/output/pdf/
