name: samm-pdf-builder
on: push
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output

        - name: "exploration"
          run: |
            echo "github.workspace is ${{ github.workspace }}"
            ls -al ${{ github.workspace }}
            ls -al ${{ github.workspace }}
         
    build:
        needs: setup
        runs-on: ubuntu-latest
        steps:
            - name: "process datafiles"
              uses: docker://nessimk/samm2cloudpdf:0.9
              with:
                args: "/static.default ${{ github.workspace }}/samm-datafiles ${{ github.workspace }}/output"
    upload:
        needs: build
        runs-on: ubuntu-latest
        steps:
        - name: upload pdf
          uses: actions/upload-artifact@v2
          with:
            name: samm2.pdf
            path: ${{ github.workspace }}/output/pdf/
