name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output

        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.10
          with:
            args: "/github/workspace/static /github/workspace/datafiles /github/workspace/output"

        - name: "create pdf name"
          run: |
            short_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo "::set-env name=pdf_filename::samm2-$short_hash.pdf"

        - name: "rename the pdf"
          run: |
            sudo mv ${{ github.workspace }}/output/pdf/samm2.pdf ${{ github.workspace }}/output/pdf/$pdf_filename
            
        - name: "upload pdf"
          uses: actions/upload-artifact@v2
          with:
            name: $pdf_filename
            path: ${{ github.workspace }}/output/pdf/
