name: samm-pdf-builder
on: push
jobs:
    build-pdf:
        runs-on: ubuntu-latest
        steps:
        - name: "checkout datafiles"
          uses: actions/checkout@v2

        - name: "create output directory"
          run: |
            mkdir ${{ github.workspace }}/output

        - name: "process datafiles"
          uses: docker://nessimk/samm2cloudpdf:0.10
          with:
            args: "/github/workspace/static /github/workspace/datafiles /github/workspace/output"

        - name: "create pdf name"
          run: |
            short_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo "samm2-${short_hash}.pdf" > ${{ github.workspace  }}/_pdf_filename

        - name: "rename the pdf"
          run: |
            pdf_filename=$(cat ${{  github.workspace  }}/_pdf_filename)
            sudo mv ${{ github.workspace }}/output/pdf/samm2.pdf ${{ github.workspace }}/output/pdf/${pdf_filename}
            
        - name: "upload pdf"
          uses: FranzDiebold/github-env-vars-action@v1.2.1
          uses: actions/upload-artifact@v2
          with:
            name: "samm2-$GITHUB_SHA_SHORT.pdf"
            path: ${{ github.workspace }}/output/pdf/
